BackendBundle\Entity\User:
    properties:
        name:
            - NotBlank: {message: "El nombre no puede estar vacio"}
        surname:
            - NotBlank: {message: "Los apellidos no pueden estar vacios"}
        nick:
            - NotBlank: {message: "El nick no puede estar vacio"}
        email:
            - NotBlank: {message: "El email no puede estar vacio"}
            - Email:
                message: El email "{{ value }}" no es v√°lido.
                checkMX: false
                
            
            